# Generated by Django 3.0.6 on 2020-09-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('contact1', models.CharField(max_length=15)),
                ('contact2', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('pincode', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
