# Generated by Django 3.0.6 on 2020-09-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='fileurl',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
